### ISSUE TITLE
HADR disabled 2

### ISSUE THREAD

**Issue by 06212** [imperva/dsfkit#386]
Hello Imperva, 

As the follow up on the issue #381, we have tried to deploy the code based on your recommandations using terraform variables:

enable_dam = false
agentless_gw_count = 0
agent_gw_count = 0
hub_hadr = false
agentless_gw_hadr = false
dra_version = "4.14"
attach_persistent_public_ip = false

aws_profile  = ""
aws_region_1 = "eu-west-1"
aws_region_2 = "eu-west-1"

/dsf_single_account_deployment$ terraform plan -var-file=default.tfvars

Here is the issue that we got: 

│ Error: Invalid index
│ 
│   on sonar.tf line 6, in locals:
│    6:   hub_dr_public_ip       = var.enable_sonar ? (length(module.hub_dr[0].public_ip) > 0 ? format("%s/32", module.hub_dr[0].public_ip) : null) : null
│     ├────────────────
│     │ module.hub_dr is empty tuple
│ 
│ The given key does not identify an element in this collection value: the collection has no elements.
╵
╷
│ Error: Invalid index
│ 
│   on sonar.tf line 10, in locals:
│   10:   hub_dr_ip              = var.enable_sonar ? (length(module.hub_dr[0].public_dns) > 0 ? module.hub_dr[0].public_dns : module.hub_dr[0].private_dns) : null
│     ├────────────────
│     │ module.hub_dr is empty tuple
│ 
│ The given key does not identify an element in this collection value: the collection has no elements.

Could you please advise how to deploy successfully Imperva infrastructure (without HADR)? 

Thank you!
Iliya

**Comment by lindanasredin** [comment]
Hi Iliya,

I fixed this bug as part of this PR: https://github.com/imperva/dsfkit/pull/388
The fix is in the example code not the modules, so you can just take and use this code and you don't have to wait for the next release of eDSF Kit.

I still see two issues that I mentioned in #381 
1. aws_profile = "" is an invalid configuration, you have to provide and AWS profile name
2. You have to provide the subnet_ids variable, more details in #381

**Comment by 06212** [comment]
Hi Linda,

Thank you for the fix.

I am not providing aws_profile because I am using temporary credentials from aws sso for deploying the infrastructure 
subnet_ids is provided with a value in the tfvar file. I just skipped it in the example because it is irrelevant outside of our organization :)

Thank you! 
Iliya

**Comment by lindanasredin** [comment]
👍
